/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package io.github.usafa_compsci350;



public class Main {

  public static void main(String[] args) {
    // variables
    int numPlayers=0;
    final int maxWalls=20;
    boolean gameOver=false;
    Scanner s = new Scanner(System.in);



      //create gameboard using ASCII
      public static void GameBoard (){
    System.out.println("  1 2 3 4 5 6 7 8 9");
    System.out.println("___________________");
    System.out.println("a|                 |");
    System.out.println("b|                 |");
    System.out.println("c|                 |");
    System.out.println("d|                 |");
    System.out.println("e|                 |");
    System.out.println("f|                 |");
    System.out.println("g|                 |");
    System.out.println("h|                 |");
    System.out.println("i|                 |");
    System.out.println("_____________________");
  }


//player Turn function

  public static void playerTurn(){
    System.out.println("Would you like to move forward(1) or place wall(2): ");
    int playerChoice= s.nextInt();
    if(playerChoice ==1){// need to learn how to use array in Java. playerChoice will be array which tracks which player is making the choice
      movePlayer();
    }
    else if (playerChoice ==2){
      placewall();
    }
    else{
      System.out.println("Enter either a 1 or 2.");
      playerTurn();
    }
  }

  }
}
